### ISSUE TITLE
Question: How to install this into Node-Red?

### ISSUE THREAD

**Issue by EvilBeaver** [andre-r-gomes/node-red-contrib-serialport-rs485#1]
Original node-red-contrib-serialport-rs485 depends on version 4.0.7 which does not exist on github. This repo does not exist on NPM. How to install this repo into Node-Red?

**Comment by andre-r-gomes** [comment]
Hi @EvilBeaver - The work around is:

sudo npm install -g n andre-r-gomes/node-red-contrib-serialport-rs485

Let me know how you get on and if it worked for you

**Comment by EvilBeaver** [comment]
It worked, thanks.
